#Gearman Servers

gearman.servers:
  - name : "1C"
    addr : "10.0.2.51"
    port : "4730"


#Supervisor Servers
#uname and password don't matter if
#supervisor is set to run without it
supervisor.servers:
  - name : "BATCH 4"
    addr : "10.0.2.16"
    port : "9001"
    uname : "admin"
    password : "admin"
  - name : "BATCH 6"
    addr : "10.0.1.17"
    port : "9001"
    uname : "admin"
    password : "admin"

bento.settings:
  refresh_interval: 5

#default log file locate in APP_DIR/logs/bento.log
# monolog.logfile: "/var/log/bento.log

# Logger level.
# Valid values: error, warning, notice, info, debug.
monolog.level: "error"